server:
  port: 8080
  
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: xianjinxia
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://116.62.117.88:3306/exchange?characterEncoding=UTF-8&&autoReconnect=true&useUnicode=true
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  a1:  
    redis:
      database: 0
      host: 116.62.117.88
      port: 7000
      password: 
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
      timeout: 0
  a2:  
    redis:
      database: 0
      host: 116.62.117.88
      port: 7001
      password: 
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
      timeout: 0
#      sentinel:
#        master: mymaster
#        nodes: 116.62.117.88:26379,116.62.117.88:26378
    
mybatis:
    type-aliases-package: com.snowstone.spring.boot.model
    mapper-locations: classpath:mapping/*.xml
  
mapper:
    mappers: com.snowstone.spring.boot.mapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    

    